config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :quotations
  root "quotations#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    elsif user.member?
      can :read, Quotation
      can :create, Quotation
      can :update, Quotation do |quotation|
        quotation.try(:user) == user
      end
      can :destroy, Quotation do |quotation|
        quotation.try(:user) == user
      end
    else
      can :read, Quotation
    end


  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quotation.rb
class Quotation < ApplicationRecord

 belongs_to :user

end

app/models/role.rb
class Role < ApplicationRecord
 has_many :users




end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role
  has_many :quotations
  before_validation :assign_role

  def assign_role
    self.role = Role.find_by_name("Member") if self.role.nil?
  end

  def admin?
    self.role.name == "Admin" if !self.role.blank?
  end

  def member?
    self.role.name == "Member" if !self.role.blank?
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Access denied."
    redirect_to '/quotations'
  end

end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  before_action :set_quotation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource
  # GET /quotations
  # GET /quotations.json
  def index
    @quotations = Quotation.all
  end

  # GET /quotations/1
  # GET /quotations/1.json
  def show
  end

  # GET /quotations/new
  def new
    @quotation = Quotation.new
  end

  # GET /quotations/1/edit
  def edit
  end

  # POST /quotations
  # POST /quotations.json
  def create


    @quotation = Quotation.new(quotation_params)
    @quotation.user = current_user
    respond_to do |format|
      if @quotation.save
        format.html { redirect_to @quotation, notice: 'Quotation was successfully created.' }
        format.json { render :show, status: :created, location: @quotation }
      else
        format.html { render :new }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotations/1
  # PATCH/PUT /quotations/1.json
  def update
    respond_to do |format|
      if @quotation.update(quotation_params)
        format.html { redirect_to @quotation, notice: 'Quotation was successfully updated.' }
        format.json { render :show, status: :ok, location: @quotation }
      else
        format.html { render :edit }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotations/1
  # DELETE /quotations/1.json
  def destroy
    @quotation.destroy
    respond_to do |format|
      format.html { redirect_to quotations_url, notice: 'Quotation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation
      @quotation = Quotation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quotation_params
      params.require(:quotation).permit(:quote)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quoteboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if flash[:error] %>
    <div id="error">
      <p><%= flash[:error] %></p>
    </div>
  <% elsif flash[:alert] %>
    <div>
      <p><%= flash[:alert] %></p>
    </div>
  <% end %>
  <div id="container">
    <% if user_signed_in? %>
      Welcome
      <%= current_user.email %>! Not you?
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %>
      or
      <%= link_to "Sign in", new_user_session_path %>.
    <% end %>
    <%= yield %>
  </div>

  </body>
</html>

app/views/quotations/_form.html.erb
<%= form_with(model: quotation, local: true) do |form| %>
  <% if quotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>

      <ul>
      <% quotation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quote %>
    <%= form.text_area :quote %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quotations/edit.html.erb
<h1>Editing Quotation</h1>

<%= render 'form', quotation: @quotation %>

<%= link_to 'Show', @quotation %> |
<%= link_to 'Back', quotations_path %>

app/views/quotations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotations</h1>

<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotations.each do |quotation| %>
      <tr>
        <td><%= quotation.quote %></td>
        <td><%= link_to 'Show', quotation %></td>
        <td><%= link_to 'Edit', edit_quotation_path(quotation) %></td>
        <td><%= link_to 'Destroy', quotation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quotation', new_quotation_path %>

app/views/quotations/new.html.erb
<h1>New Quotation</h1>

<%= render 'form', quotation: @quotation %>

<%= link_to 'Back', quotations_path %>

app/views/quotations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @quotation.quote %>
</p>

<%= link_to 'Edit', edit_quotation_path(@quotation) %> |
<%= link_to 'Back', quotations_path %>